# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dadoun/Programs/geant4/XeB2B

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dadoun/Programs/geant4/XeB2B

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dadoun/Programs/geant4/XeB2B/CMakeFiles /Users/dadoun/Programs/geant4/XeB2B//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dadoun/Programs/geant4/XeB2B/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xeb2b

# Build rule for target.
xeb2b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xeb2b
.PHONY : xeb2b

# fast build rule for target.
xeb2b/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/build
.PHONY : xeb2b/fast

src/XeB2BDetectorConstruction.o: src/XeB2BDetectorConstruction.cc.o
.PHONY : src/XeB2BDetectorConstruction.o

# target to build an object file
src/XeB2BDetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/src/XeB2BDetectorConstruction.cc.o
.PHONY : src/XeB2BDetectorConstruction.cc.o

src/XeB2BDetectorConstruction.i: src/XeB2BDetectorConstruction.cc.i
.PHONY : src/XeB2BDetectorConstruction.i

# target to preprocess a source file
src/XeB2BDetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/src/XeB2BDetectorConstruction.cc.i
.PHONY : src/XeB2BDetectorConstruction.cc.i

src/XeB2BDetectorConstruction.s: src/XeB2BDetectorConstruction.cc.s
.PHONY : src/XeB2BDetectorConstruction.s

# target to generate assembly for a file
src/XeB2BDetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/src/XeB2BDetectorConstruction.cc.s
.PHONY : src/XeB2BDetectorConstruction.cc.s

src/XeB2BPhysicsList.o: src/XeB2BPhysicsList.cc.o
.PHONY : src/XeB2BPhysicsList.o

# target to build an object file
src/XeB2BPhysicsList.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/src/XeB2BPhysicsList.cc.o
.PHONY : src/XeB2BPhysicsList.cc.o

src/XeB2BPhysicsList.i: src/XeB2BPhysicsList.cc.i
.PHONY : src/XeB2BPhysicsList.i

# target to preprocess a source file
src/XeB2BPhysicsList.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/src/XeB2BPhysicsList.cc.i
.PHONY : src/XeB2BPhysicsList.cc.i

src/XeB2BPhysicsList.s: src/XeB2BPhysicsList.cc.s
.PHONY : src/XeB2BPhysicsList.s

# target to generate assembly for a file
src/XeB2BPhysicsList.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/src/XeB2BPhysicsList.cc.s
.PHONY : src/XeB2BPhysicsList.cc.s

src/XeB2BPrimaryGeneratorAction.o: src/XeB2BPrimaryGeneratorAction.cc.o
.PHONY : src/XeB2BPrimaryGeneratorAction.o

# target to build an object file
src/XeB2BPrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/src/XeB2BPrimaryGeneratorAction.cc.o
.PHONY : src/XeB2BPrimaryGeneratorAction.cc.o

src/XeB2BPrimaryGeneratorAction.i: src/XeB2BPrimaryGeneratorAction.cc.i
.PHONY : src/XeB2BPrimaryGeneratorAction.i

# target to preprocess a source file
src/XeB2BPrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/src/XeB2BPrimaryGeneratorAction.cc.i
.PHONY : src/XeB2BPrimaryGeneratorAction.cc.i

src/XeB2BPrimaryGeneratorAction.s: src/XeB2BPrimaryGeneratorAction.cc.s
.PHONY : src/XeB2BPrimaryGeneratorAction.s

# target to generate assembly for a file
src/XeB2BPrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/src/XeB2BPrimaryGeneratorAction.cc.s
.PHONY : src/XeB2BPrimaryGeneratorAction.cc.s

xeb2b.o: xeb2b.cc.o
.PHONY : xeb2b.o

# target to build an object file
xeb2b.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/xeb2b.cc.o
.PHONY : xeb2b.cc.o

xeb2b.i: xeb2b.cc.i
.PHONY : xeb2b.i

# target to preprocess a source file
xeb2b.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/xeb2b.cc.i
.PHONY : xeb2b.cc.i

xeb2b.s: xeb2b.cc.s
.PHONY : xeb2b.s

# target to generate assembly for a file
xeb2b.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xeb2b.dir/build.make CMakeFiles/xeb2b.dir/xeb2b.cc.s
.PHONY : xeb2b.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xeb2b"
	@echo "... src/XeB2BDetectorConstruction.o"
	@echo "... src/XeB2BDetectorConstruction.i"
	@echo "... src/XeB2BDetectorConstruction.s"
	@echo "... src/XeB2BPhysicsList.o"
	@echo "... src/XeB2BPhysicsList.i"
	@echo "... src/XeB2BPhysicsList.s"
	@echo "... src/XeB2BPrimaryGeneratorAction.o"
	@echo "... src/XeB2BPrimaryGeneratorAction.i"
	@echo "... src/XeB2BPrimaryGeneratorAction.s"
	@echo "... xeb2b.o"
	@echo "... xeb2b.i"
	@echo "... xeb2b.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

