#
# Macro file for visualization (interactive mode)
#
/control/verbose 2
/run/verbose 2
#
# Create a scene handler for DAWNFILE (file-based output)
#
/vis/open DAWNFILE
#
# create empty scene
/vis/scene/create
#
# draw scene
#
/vis/viewer/set/viewpointThetaPhi 90 90
/vis/viewer/zoom 1.4
/vis/viewer/flush
/vis/geometry/set/visibility World 0 true

#
# for drawing the tracks
#
/tracking/storeTrajectory 1
/vis/scene/add/trajectories

# Run one event
/run/beamOn 1
